create table if not exists public.check_ins (
  id bigint generated by default as identity primary key,
  pillar text not null check (pillar in ('intellectual','financial','physical','creative','social','spiritual','entertainment')),
  completed boolean not null default true,
  score smallint not null check (score between 0 and 100),
  created_at timestamptz not null default now()
);

alter table public.check_ins enable row level security;
grant insert on table public.check_ins to anon;
grant usage, select on sequence public.check_ins_id_seq to anon;

create policy "Visitors can create valid check-ins"
on public.check_ins for insert
to anon
with check (
  pillar in ('intellectual','financial','physical','creative','social','spiritual','entertainment')
  and score between 0 and 100
  and completed in (true, false)
);

revoke select, update, delete on table public.check_ins from anon;
